name: 'Docker Build'
# act -j build -W ./.github/workflows/docker.yaml --secret-file  .dockerhub.secrets

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                type: [ dev, prod ]
                server: [ fpm, apache ]
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  build-args: |
                      KIMAI=${{ env.kimai_version }}
                      TIMEZONE=Europe/London
                      BASE=${{ matrix.server }}
                  target: ${{ matrix.type }}
                  platforms: linux/amd64,linux/arm64 #,linux/arm/v8,linux/arm/v7,linux/arm/v6
                  tags: |
                      kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}-unstable
                  push: true

    test:
        strategy:
            matrix:
                type: [ dev, prod ]
                server: [ fpm, apache ]
        runs-on: ubuntu-latest

        steps:

            - name: Pull images
              run: docker pull kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}-unstable

            - name: Test Lite
              run: docker run --rm --entrypoint /self-test.sh kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}-unstable
